---
#- name: get report
#  set_fact:
#    report: "{{ lookup('file','/tmp/report.txt') | from_yaml }}"

#- debug:
#    msg: "{{ report }}"

- name: ping 'em all (short)
  shell: "ping -c 5 -q {{ hostvars[item].ansible_hostname}}"
  register: ping_result_short

- name: set ping success
  set_fact:
    ping_success: "{{ ping_result_short.stdout_lines[3] | regex_findall('[0-9]{1,3}%')| regex_replace('%') | int}}"

- set_fact:
    bad_ping_sort: "ping from {{ inventory_hostname }} to {{ hostvars[item].ansible_hostname}} is bad"
  when: ping_success | int >= 10

- set_fact:
    report.ping_to_long_names

- lineinfile:
    path: /tmp/report.txt
    line: "    {{ ping_success }} lost packets from {{ inventory_hostname }} to {{ hostvars[item].ansible_hostname}}"
    insertafter: '^  ping_to_short_names:'
#    insertbefore: '^ping_to_long_names:'
  delegate_to: 127.0.0.1

- name: ping 'em all (long)
  shell: "ping -c 5 -q {{ hostvars[item].ansible_fqdn}}"
  register: ping_result_long

- name: set ping success
  set_fact:
    ping_success: "{{ ping_result_long.stdout_lines[3] | regex_findall('[0-9]{1,3}%')| regex_replace('%') | int}}"

- set_fact:
    bad_ping_long: "ping from {{ inventory_hostname }} to {{ hostvars[item].ansible_fqdn}} is bad"
  when: ping_success | int >= 10

- set_fact:
    bla:
      - "    -from: {{ inventory_hostname }}"
      - "     to: {{ hostvars[item].ansible_fqdn}}"
      - "     lost: {{ ping_success }}"
    
- lineinfile:
    path: /tmp/report.txt
    line: "{{ bla }}"
    insertafter: '^  ping_to_long_names:'
  delegate_to: 127.0.0.1

- debug:
    msg: "{{ bad_ping_long }}"
  when: bad_ping_long is defined

- name: ping the internet
  shell: "ping -c 5 -q 8.8.8.8"
  register: ping_result_internet

- name: set ping success
  set_fact:
    ping_success: "{{ ping_result_internet.stdout_lines[3] | regex_findall('[0-9]{1,3}%')| regex_replace('%') | int}}"

- set_fact:
    bad_ping_long: "ping from {{ inventory_hostname }} to 8.8.8.8"
  when: ping_success | int >= 10

- lineinfile:
    path: /tmp/report.txt
    line: "    {{ ping_success }} lost packets from {{ inventory_hostname }} to 8.8.8.8"
    insertafter: '^  ping_to_internet:'
  delegate_to: 127.0.0.1

- debug:
    msg: "{{ bad_ping_long }}"
  when: bad_ping_long is defined
