---
- name: "install {{ openstack_sku }} specific repos"
  yum:
    name: "centos-release-openstack-{{ openstack_sku }}"
    state: latest

- name: install packages required by kolla playbooks
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - gcc
    - python-devel
    - python-oslo-config
    - python-oslo-utils
    - python-pip

- name: install right version of jinja2 for kolla
  pip:
    name: jinja2
    extra_args: --upgrade

- name: install pycrypto to generate passwords
  pip:
    name: pycrypto
    state: latest
