# orchestrator MUST be passed as a command line argument like so:
#
# ansible-playbook -i inventory/ -e orchestrator=openstack playbook/install_k8s.yml
#
# orchestrator can be openstack or kubernetes
#
- name: Create container host group
  hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Expose instances
      set_fact:
          instances: "{{ instances }}"
      when: hostvars['localhost']['instances'] is undefined
  roles:
    - name: Generate container_host group
      role: create_container_host_group
  vars_files:
    - "{{ config_file }}"
  tags: always

# TODO: create role for k8s installing and use it here
